apiVersion: v1
kind: Service
metadata:
  name: qr-gen-service
  labels:
    app: qr-gen-app
spec:
  selector:
    app: qr-gen-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: qr-gen-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qr-gen-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80  # Target CPU utilization percentage